# Generated by Django 5.0.2 on 2024-03-07 09:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("S_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("036e4ede-6d5c-4da3-b33a-cb84a46ad2ec"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="posts")),
                ("caption", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 3, 7, 9, 22, 9, 22296)
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
